source 'http://rubygems.org'

gem "jquery-rails"
gem "haml-rails"
gem "sass-rails"
gem "compass", ">= 0.12.alpha.4"
gem "coffee-rails"
gem "execjs"
gem "paper_trail"
gem "simple_form"
gem "factory_girl_rails"
gem "rails3-generators"
gem "devise", "~> 2.0.0.rc"
gem "cancan"
gem "redcarpet"
gem "awesome_print"

gem "sqlite3"
gem "rspec-rails"
gem "capybara"
gem "launchy"
gem "database_cleaner"
gem "eventmachine" #, ">= 1.0.0.beta.4.1"
gem "thin"