source 'http://rubygems.org'

gem "jquery-rails"
gem "haml-rails"
gem "sass-rails"
gem "compass-rails"
gem "coffee-rails"
gem "execjs"
gem "paper_trail"
gem "simple_form"
gem "rails3-generators"
gem "redcarpet"
gem "rdiscount"
gem "acts-as-taggable-on"
gem "bcrypt-ruby"

group :test do
  gem "sqlite3"
  gem "factory_girl_rails"
  gem "faker"
  gem "awesome_print"
  gem "rspec-rails"
  gem "capybara"
  gem "cucumber-rails"
  gem "launchy"
  gem "database_cleaner"
  gem "cucumber"
  gem "fuubar"
  gem "fuubar-cucumber"
end